### ISSUE TITLE
Statuses `pending` and `todo` are unhandled

### ISSUE THREAD

**Issue by piranna** [MatteoH2O1999/github-actions-jest-reporter#173]
At https://github.com/MatteoH2O1999/github-actions-jest-reporter/blob/8612553963c2786acfd5829c93fe6a4e6abe7f40/src/gha.reporter.ts#L134-L141, if a test status is different of `pending` or `todo`, an exception is thrown, leading Jest to fail also if all the tests have passed. The `pending` one can be a failure on my side if I could have not properly cleaned the test environment and there are some remaining async operations, but `todo` is totally fine since the test has not been executed, so it should be handled and not crash. The most simple fix would be to just ignore it, but if we want to show it someway in the report, we can use the cristal ball emoji 🔮, not only as showing something in the future, but also has the same purple color that's being used by Jest for `todo` tests :-)

**Comment by MatteoH2O1999** [comment]
Should be now fixed with [v3.0.0](https://github.com/MatteoH2O1999/github-actions-jest-reporter/releases/tag/v3.0.0)

**Comment by piranna** [comment]
> Should be now fixed with [v3.0.0](https://github.com/MatteoH2O1999/github-actions-jest-reporter/releases/tag/v3.0.0)

Yes, it seems to be fixed, thanks :-)
